# Generated by Django 4.0.6 on 2023-04-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web3User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('web3_address', models.CharField(max_length=100, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_broker', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BNB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(max_length=1000)),
                ('rank', models.CharField(choices=[('PACKAGE 1', 'GOLD'), ('PACKAGE 2', 'RUBY'), ('PACKAGE 3', 'PLATINUM'), ('PACKAGE 4', 'SAPPHIRE'), ('PACKAGE 5', 'DIAMOND'), ('PACKAGE 6', 'DOUBLE DIAMOND')], max_length=100)),
                ('click_link', models.ManyToManyField(related_name='user_click', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
